# Generated by Django 3.2.7 on 2021-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20211009_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tables', models.IntegerField()),
            ],
        ),
    ]
