# Generated by Django 3.2.7 on 2021-10-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_mastertables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterTables',
            new_name='MasterTable',
        ),
    ]
